version: '3.4'

services:
    db:
        image: postgres:12
        container_name: pg-yop
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=yop
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev
