version: '3.4'

services:
    db:
        image: postgres:12
        container_name: pg-yop
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=yop
            - POSTGRES_USER=dev
            - POSTGRES_PASSWORD=dev

    dev:
        build: support
        image: ubuntu:yop
        container_name: ubuntu-yop
        environment:
            - POSTGRES_URL=postgres://dev:dev@host.docker.internal:5433/yop
        ports:
            - 5001:5001
        volumes:
            - ./package.json:/root/code/package.json
            - ./package-lock.json:/root/code/package-lock.json
            - ./.nvmrc:/root/code/.nvmrc
            - ./support/run.sh:/root/code/run.sh
            - ./about:/root/code/about
            - ./brag:/root/code/brag
            - ./dist:/root/code/dist
