name: CI

on:
    push:
        branches:
            - dev

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_DB: yop
                    POSTGRES_USER: dev
                    POSTGRES_PASSWORD: dev
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            POSTGRES_URL: postgres://dev:dev@localhost:5432/yop

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: install node
              uses: actions/setup-node@v2
              with:
                  node-version-file: '.nvmrc'
            - name: info
              run: |
                  node --version
                  npm --version
            - name: install
              run: |
                  npm install
            - name: tests
              run: |
                  npm test
