name: CI

on:
    push:
        branches:
            - dev

jobs:
    test:
        name: run tests
        runs-on: ubuntu-20.04

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: update /etc/hosts
              run: |
                  sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
                  cat /etc/hosts
            - name: start db
              run: docker-compose up -d db
            - name: wait for db
              run: ./support/wait.sh
            - name: build dev environment
              run: docker-compose build dev
            - name: tests
              run: docker-compose run --rm --name ubuntu-yop dev ./run.sh
